version: 'latest'

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: baonguyen
      MONGO_INITDB_ROOT_PASSWORD: 123
    volumes:
      - mongo:/mongo/data

volumes:
  mongo: